# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - release
  paths:
    include:
    - 'KenticoAdmin/*' # same as '/' for the repository root

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/WebApp.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

# DO NOT CACHE for this .net 4.8 build, as the MSBuild command will blow up when the project.assets.json file is required and built using the nuget restore.
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# This renames the AppSettings.Template/ConnectionStrings.Template (empty template tracked in source) to AppSettings.Config/ConnectionStrings.Config (Included in build project but not tracked in source)
# this is so the Release can fill these with the settings from Variables
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-Location
      Get-ChildItem -Path ./ -Filter *.template -Recurse -File -Name | ForEach-Object {
          $newName = $_.Replace(".template", ".config")
          $fileName = Split-Path $newName -leaf
          Write-Host $fileName ">" $newName
          Rename-Item $_ -NewName $fileName
      }

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'