//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.SectionsSystem;

[assembly: RegisterDocumentType(BasicElementLink.CLASS_NAME, typeof(BasicElementLink))]

namespace CMS.DocumentEngine.Types.SectionsSystem
{
    /// <summary>
    /// Represents a content item of type BasicElementLink.
    /// </summary>
    public partial class BasicElementLink : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "SectionsSystem.BasicElementLink";


        /// <summary>
        /// The instance of the class that provides extended API for working with BasicElementLink fields.
        /// </summary>
        private readonly BasicElementLinkFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// BasicElementLinkID.
        /// </summary>
        [DatabaseIDField]
        public int BasicElementLinkID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("BasicElementLinkID"), 0);
            }
            set
            {
                SetValue("BasicElementLinkID", value);
            }
        }


        /// <summary>
        /// Link Name.
        /// </summary>
        [DatabaseField]
        public string LinkName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkName"), @"");
            }
            set
            {
                SetValue("LinkName", value);
            }
        }


        /// <summary>
        /// Link Text.
        /// </summary>
        [DatabaseField]
        public string LinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkText"), @"");
            }
            set
            {
                SetValue("LinkText", value);
            }
        }


        /// <summary>
        /// Button = Button styled link
        /// 
        /// Text = Text Link
        /// 
        /// General = Just a link, this type is often used if the entire Section Item is to be linked.
        /// </summary>
        [DatabaseField]
        public string LinkType
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkType"), @"Button");
            }
            set
            {
                SetValue("LinkType", value);
            }
        }


        /// <summary>
        /// LInk Url.
        /// </summary>
        [DatabaseField]
        public string LinkUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkUrl"), @"");
            }
            set
            {
                SetValue("LinkUrl", value);
            }
        }


        /// <summary>
        /// Link Target.
        /// </summary>
        [DatabaseField]
        public string LinkTarget
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkTarget"), @"_self");
            }
            set
            {
                SetValue("LinkTarget", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with BasicElementLink fields.
        /// </summary>
        [RegisterProperty]
        public BasicElementLinkFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with BasicElementLink fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class BasicElementLinkFields : AbstractHierarchicalObject<BasicElementLinkFields>
        {
            /// <summary>
            /// The content item of type BasicElementLink that is a target of the extended API.
            /// </summary>
            private readonly BasicElementLink mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="BasicElementLinkFields" /> class with the specified content item of type BasicElementLink.
            /// </summary>
            /// <param name="instance">The content item of type BasicElementLink that is a target of the extended API.</param>
            public BasicElementLinkFields(BasicElementLink instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// BasicElementLinkID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.BasicElementLinkID;
                }
                set
                {
                    mInstance.BasicElementLinkID = value;
                }
            }


            /// <summary>
            /// Link Name.
            /// </summary>
            public string LinkName
            {
                get
                {
                    return mInstance.LinkName;
                }
                set
                {
                    mInstance.LinkName = value;
                }
            }


            /// <summary>
            /// Link Text.
            /// </summary>
            public string LinkText
            {
                get
                {
                    return mInstance.LinkText;
                }
                set
                {
                    mInstance.LinkText = value;
                }
            }


            /// <summary>
            /// Button = Button styled link
            /// 
            /// Text = Text Link
            /// 
            /// General = Just a link, this type is often used if the entire Section Item is to be linked.
            /// </summary>
            public string LinkType
            {
                get
                {
                    return mInstance.LinkType;
                }
                set
                {
                    mInstance.LinkType = value;
                }
            }


            /// <summary>
            /// LInk Url.
            /// </summary>
            public string LinkUrl
            {
                get
                {
                    return mInstance.LinkUrl;
                }
                set
                {
                    mInstance.LinkUrl = value;
                }
            }


            /// <summary>
            /// Link Target.
            /// </summary>
            public string LinkTarget
            {
                get
                {
                    return mInstance.LinkTarget;
                }
                set
                {
                    mInstance.LinkTarget = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="BasicElementLink" /> class.
        /// </summary>
        public BasicElementLink() : base(CLASS_NAME)
        {
            mFields = new BasicElementLinkFields(this);
        }

        #endregion
    }
}