//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.SectionsSystem;

[assembly: RegisterDocumentType(FeatureItem.CLASS_NAME, typeof(FeatureItem))]

namespace CMS.DocumentEngine.Types.SectionsSystem
{
    /// <summary>
    /// Represents a content item of type FeatureItem.
    /// </summary>
    public partial class FeatureItem : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "SectionsSystem.FeatureItem";


        /// <summary>
        /// The instance of the class that provides extended API for working with FeatureItem fields.
        /// </summary>
        private readonly FeatureItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// FeatureItemID.
        /// </summary>
        [DatabaseIDField]
        public int FeatureItemID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("FeatureItemID"), 0);
            }
            set
            {
                SetValue("FeatureItemID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string FeatureItemTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemTitle"), @"");
            }
            set
            {
                SetValue("FeatureItemTitle", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string FeatureItemDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemDescription"), @"");
            }
            set
            {
                SetValue("FeatureItemDescription", value);
            }
        }


        /// <summary>
        /// Icon Source.
        /// </summary>
        [DatabaseField]
        public string FeatureItemIconSource
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemIconSource"), @"FontAwesome");
            }
            set
            {
                SetValue("FeatureItemIconSource", value);
            }
        }


        /// <summary>
        /// What the icon is (ex 'star' or 'dollar sign').
        /// </summary>
        [DatabaseField]
        public string FeatureItemIconAlt
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemIconAlt"), @"");
            }
            set
            {
                SetValue("FeatureItemIconAlt", value);
            }
        }


        /// <summary>
        /// Font Awesome Icon Code.
        /// </summary>
        [DatabaseField]
        public string FeatureItemFontAwesomeIconCode
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemFontAwesomeIconCode"), @"");
            }
            set
            {
                SetValue("FeatureItemFontAwesomeIconCode", value);
            }
        }


        /// <summary>
        /// Canvas Code.
        /// </summary>
        [DatabaseField]
        public string FeatureItemCanvasIconCode
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemCanvasIconCode"), @"");
            }
            set
            {
                SetValue("FeatureItemCanvasIconCode", value);
            }
        }


        /// <summary>
        /// Custom Icon Code.
        /// </summary>
        [DatabaseField]
        public string FeatureItemCustomIconCode
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemCustomIconCode"), @"");
            }
            set
            {
                SetValue("FeatureItemCustomIconCode", value);
            }
        }


        /// <summary>
        /// LInk Url.
        /// </summary>
        [DatabaseField]
        public string FeatureItemLinkUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemLinkUrl"), @"");
            }
            set
            {
                SetValue("FeatureItemLinkUrl", value);
            }
        }


        /// <summary>
        /// Link Target.
        /// </summary>
        [DatabaseField]
        public string FeatureItemLinkTarget
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FeatureItemLinkTarget"), @"_self");
            }
            set
            {
                SetValue("FeatureItemLinkTarget", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with FeatureItem fields.
        /// </summary>
        [RegisterProperty]
        public FeatureItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with FeatureItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class FeatureItemFields : AbstractHierarchicalObject<FeatureItemFields>
        {
            /// <summary>
            /// The content item of type FeatureItem that is a target of the extended API.
            /// </summary>
            private readonly FeatureItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="FeatureItemFields" /> class with the specified content item of type FeatureItem.
            /// </summary>
            /// <param name="instance">The content item of type FeatureItem that is a target of the extended API.</param>
            public FeatureItemFields(FeatureItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// FeatureItemID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.FeatureItemID;
                }
                set
                {
                    mInstance.FeatureItemID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.FeatureItemTitle;
                }
                set
                {
                    mInstance.FeatureItemTitle = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.FeatureItemDescription;
                }
                set
                {
                    mInstance.FeatureItemDescription = value;
                }
            }


            /// <summary>
            /// Icon Source.
            /// </summary>
            public string IconSource
            {
                get
                {
                    return mInstance.FeatureItemIconSource;
                }
                set
                {
                    mInstance.FeatureItemIconSource = value;
                }
            }


            /// <summary>
            /// What the icon is (ex 'star' or 'dollar sign').
            /// </summary>
            public string IconAlt
            {
                get
                {
                    return mInstance.FeatureItemIconAlt;
                }
                set
                {
                    mInstance.FeatureItemIconAlt = value;
                }
            }


            /// <summary>
            /// Font Awesome Icon Code.
            /// </summary>
            public string FontAwesomeIconCode
            {
                get
                {
                    return mInstance.FeatureItemFontAwesomeIconCode;
                }
                set
                {
                    mInstance.FeatureItemFontAwesomeIconCode = value;
                }
            }


            /// <summary>
            /// Canvas Code.
            /// </summary>
            public string CanvasIconCode
            {
                get
                {
                    return mInstance.FeatureItemCanvasIconCode;
                }
                set
                {
                    mInstance.FeatureItemCanvasIconCode = value;
                }
            }


            /// <summary>
            /// Custom Icon Code.
            /// </summary>
            public string CustomIconCode
            {
                get
                {
                    return mInstance.FeatureItemCustomIconCode;
                }
                set
                {
                    mInstance.FeatureItemCustomIconCode = value;
                }
            }


            /// <summary>
            /// LInk Url.
            /// </summary>
            public string LinkUrl
            {
                get
                {
                    return mInstance.FeatureItemLinkUrl;
                }
                set
                {
                    mInstance.FeatureItemLinkUrl = value;
                }
            }


            /// <summary>
            /// Link Target.
            /// </summary>
            public string LinkTarget
            {
                get
                {
                    return mInstance.FeatureItemLinkTarget;
                }
                set
                {
                    mInstance.FeatureItemLinkTarget = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureItem" /> class.
        /// </summary>
        public FeatureItem() : base(CLASS_NAME)
        {
            mFields = new FeatureItemFields(this);
        }

        #endregion
    }
}