//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Generic;

[assembly: RegisterDocumentType(Folder.CLASS_NAME, typeof(Folder))]

namespace CMS.DocumentEngine.Types.Generic
{
	/// <summary>
	/// Represents a content item of type Folder.
	/// </summary>
	public partial class Folder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Generic.Folder";


		/// <summary>
		/// The instance of the class that provides extended API for working with Folder fields.
		/// </summary>
		private readonly FolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FolderID.
		/// </summary>
		[DatabaseIDField]
		public int FolderID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("FolderID"), 0);
			}
			set
			{
				SetValue("FolderID", value);
			}
		}


		/// <summary>
		/// Folder Name.
		/// </summary>
		[DatabaseField]
		public string FolderName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FolderName"), @"");
			}
			set
			{
				SetValue("FolderName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Folder fields.
		/// </summary>
		[RegisterProperty]
		public FolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Folder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FolderFields : AbstractHierarchicalObject<FolderFields>
		{
			/// <summary>
			/// The content item of type Folder that is a target of the extended API.
			/// </summary>
			private readonly Folder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FolderFields" /> class with the specified content item of type Folder.
			/// </summary>
			/// <param name="instance">The content item of type Folder that is a target of the extended API.</param>
			public FolderFields(Folder instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FolderID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.FolderID;
				}
				set
				{
					mInstance.FolderID = value;
				}
			}


			/// <summary>
			/// Folder Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.FolderName;
				}
				set
				{
					mInstance.FolderName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Folder" /> class.
		/// </summary>
		public Folder() : base(CLASS_NAME)
		{
			mFields = new FolderFields(this);
		}

		#endregion
	}
}