//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Generic;

[assembly: RegisterDocumentType(Tab.CLASS_NAME, typeof(Tab))]

namespace CMS.DocumentEngine.Types.Generic
{
	/// <summary>
	/// Represents a content item of type Tab.
	/// </summary>
	public partial class Tab : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Generic.Tab";


		/// <summary>
		/// The instance of the class that provides extended API for working with Tab fields.
		/// </summary>
		private readonly TabFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TabID.
		/// </summary>
		[DatabaseIDField]
		public int TabID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TabID"), 0);
			}
			set
			{
				SetValue("TabID", value);
			}
		}


		/// <summary>
		/// Tab Name.
		/// </summary>
		[DatabaseField]
		public string TabName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TabName"), @"");
			}
			set
			{
				SetValue("TabName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Tab fields.
		/// </summary>
		[RegisterProperty]
		public TabFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Tab fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TabFields : AbstractHierarchicalObject<TabFields>
		{
			/// <summary>
			/// The content item of type Tab that is a target of the extended API.
			/// </summary>
			private readonly Tab mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TabFields" /> class with the specified content item of type Tab.
			/// </summary>
			/// <param name="instance">The content item of type Tab that is a target of the extended API.</param>
			public TabFields(Tab instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TabID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TabID;
				}
				set
				{
					mInstance.TabID = value;
				}
			}


			/// <summary>
			/// Tab Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.TabName;
				}
				set
				{
					mInstance.TabName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Tab" /> class.
		/// </summary>
		public Tab() : base(CLASS_NAME)
		{
			mFields = new TabFields(this);
		}

		#endregion
	}
}