//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Generic;

[assembly: RegisterDocumentType(TabParent.CLASS_NAME, typeof(TabParent))]

namespace CMS.DocumentEngine.Types.Generic
{
	/// <summary>
	/// Represents a content item of type TabParent.
	/// </summary>
	public partial class TabParent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Generic.TabParent";


		/// <summary>
		/// The instance of the class that provides extended API for working with TabParent fields.
		/// </summary>
		private readonly TabParentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TabParentID.
		/// </summary>
		[DatabaseIDField]
		public int TabParentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TabParentID"), 0);
			}
			set
			{
				SetValue("TabParentID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string TabParentName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TabParentName"), @"");
			}
			set
			{
				SetValue("TabParentName", value);
			}
		}


		/// <summary>
		/// Required to have one field that isn't a database only field... this is it.
		/// </summary>
		[DatabaseField]
		public bool UsesBaseInheritedPage
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("UsesBaseInheritedPage"), true);
			}
			set
			{
				SetValue("UsesBaseInheritedPage", value);
			}
		}


		/// <summary>
		/// If empty, will default to the Properties -> Metadata -> Page title, followed by the Document Name.
		/// </summary>
		public string MetaData_Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MetaData_Title"), @"");
			}
			set
			{
				SetValue("MetaData_Title", value);
			}
		}


		/// <summary>
		/// If empty, will default to the Properties -> Metadata -> Page description.
		/// </summary>
		public string MetaData_Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MetaData_Description"), @"");
			}
			set
			{
				SetValue("MetaData_Description", value);
			}
		}


		/// <summary>
		/// If empty, will default to the Properties -> Metadata -> Page keywords.
		/// </summary>
		public string MetaData_Keywords
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MetaData_Keywords"), @"");
			}
			set
			{
				SetValue("MetaData_Keywords", value);
			}
		}


		/// <summary>
		/// Should be 1280×720, JPEG PNG or GIF.
		/// 
		/// Can be overwritten manually within MVC view if thumbnail derived from a different source.
		/// </summary>
		public string MetaData_ThumbnailSmall
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MetaData_ThumbnailSmall"), @"");
			}
			set
			{
				SetValue("MetaData_ThumbnailSmall", value);
			}
		}


		/// <summary>
		/// This is not used currently for SEO meta tags, but can be useful for other things within your site.
		/// </summary>
		public string MetaData_ThumbnailLarge
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MetaData_ThumbnailLarge"), @"");
			}
			set
			{
				SetValue("MetaData_ThumbnailLarge", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TabParent fields.
		/// </summary>
		[RegisterProperty]
		public TabParentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TabParent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TabParentFields : AbstractHierarchicalObject<TabParentFields>
		{
			/// <summary>
			/// The content item of type TabParent that is a target of the extended API.
			/// </summary>
			private readonly TabParent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TabParentFields" /> class with the specified content item of type TabParent.
			/// </summary>
			/// <param name="instance">The content item of type TabParent that is a target of the extended API.</param>
			public TabParentFields(TabParent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TabParentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TabParentID;
				}
				set
				{
					mInstance.TabParentID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.TabParentName;
				}
				set
				{
					mInstance.TabParentName = value;
				}
			}


			/// <summary>
			/// Required to have one field that isn't a database only field... this is it.
			/// </summary>
			public bool UsesBaseInheritedPage
			{
				get
				{
					return mInstance.UsesBaseInheritedPage;
				}
				set
				{
					mInstance.UsesBaseInheritedPage = value;
				}
			}


			/// <summary>
			/// If empty, will default to the Properties -> Metadata -> Page title, followed by the Document Name.
			/// </summary>
			public string MetaData_Title
			{
				get
				{
					return mInstance.MetaData_Title;
				}
				set
				{
					mInstance.MetaData_Title = value;
				}
			}


			/// <summary>
			/// If empty, will default to the Properties -> Metadata -> Page description.
			/// </summary>
			public string MetaData_Description
			{
				get
				{
					return mInstance.MetaData_Description;
				}
				set
				{
					mInstance.MetaData_Description = value;
				}
			}


			/// <summary>
			/// If empty, will default to the Properties -> Metadata -> Page keywords.
			/// </summary>
			public string MetaData_Keywords
			{
				get
				{
					return mInstance.MetaData_Keywords;
				}
				set
				{
					mInstance.MetaData_Keywords = value;
				}
			}


			/// <summary>
			/// Should be 1280×720, JPEG PNG or GIF.
			/// 
			/// Can be overwritten manually within MVC view if thumbnail derived from a different source.
			/// </summary>
			public string MetaData_ThumbnailSmall
			{
				get
				{
					return mInstance.MetaData_ThumbnailSmall;
				}
				set
				{
					mInstance.MetaData_ThumbnailSmall = value;
				}
			}


			/// <summary>
			/// This is not used currently for SEO meta tags, but can be useful for other things within your site.
			/// </summary>
			public string MetaData_ThumbnailLarge
			{
				get
				{
					return mInstance.MetaData_ThumbnailLarge;
				}
				set
				{
					mInstance.MetaData_ThumbnailLarge = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TabParent" /> class.
		/// </summary>
		public TabParent() : base(CLASS_NAME)
		{
			mFields = new TabParentFields(this);
		}

		#endregion
	}
}