//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Generic;

[assembly: RegisterDocumentType(CMS.DocumentEngine.Types.Generic.ShareableContent.CLASS_NAME, typeof(CMS.DocumentEngine.Types.Generic.ShareableContent))]

namespace CMS.DocumentEngine.Types.Generic
{
	/// <summary>
	/// Represents a content item of type ShareableContent.
	/// </summary>
	public partial class ShareableContent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Generic.ShareableContent";


		/// <summary>
		/// The instance of the class that provides extended API for working with ShareableContent fields.
		/// </summary>
		private readonly ShareableContentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ShareableContentID.
		/// </summary>
		[DatabaseIDField]
		public int ShareableContentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ShareableContentID"), 0);
			}
			set
			{
				SetValue("ShareableContentID", value);
			}
		}


		/// <summary>
		/// Content Name.
		/// </summary>
		[DatabaseField]
		public string ShareableContentName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ShareableContentName"), @"");
			}
			set
			{
				SetValue("ShareableContentName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ShareableContent fields.
		/// </summary>
		[RegisterProperty]
		public ShareableContentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ShareableContent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ShareableContentFields : AbstractHierarchicalObject<ShareableContentFields>
		{
			/// <summary>
			/// The content item of type ShareableContent that is a target of the extended API.
			/// </summary>
			private readonly ShareableContent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ShareableContentFields" /> class with the specified content item of type ShareableContent.
			/// </summary>
			/// <param name="instance">The content item of type ShareableContent that is a target of the extended API.</param>
			public ShareableContentFields(ShareableContent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ShareableContentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ShareableContentID;
				}
				set
				{
					mInstance.ShareableContentID = value;
				}
			}


			/// <summary>
			/// Content Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.ShareableContentName;
				}
				set
				{
					mInstance.ShareableContentName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ShareableContent" /> class.
		/// </summary>
		public ShareableContent() : base(CLASS_NAME)
		{
			mFields = new ShareableContentFields(this);
		}

		#endregion
	}
}