//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.Generic;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Header.CLASS_NAME, typeof(Header))]

namespace CMS.DocumentEngine.Types.Generic
{
    /// <summary>
    /// Represents a content item of type Header.
    /// </summary>
    public partial class Header : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "Generic.Header";


        /// <summary>
        /// The instance of the class that provides extended API for working with Header fields.
        /// </summary>
        private readonly HeaderFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// HeaderID.
        /// </summary>
        [DatabaseIDField]
        public int HeaderID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("HeaderID"), 0);
            }
            set
            {
                SetValue("HeaderID", value);
            }
        }


        /// <summary>
        /// Node Name.
        /// </summary>
        [DatabaseField]
        public string HeaderName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HeaderName"), @"");
            }
            set
            {
                SetValue("HeaderName", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Header fields.
        /// </summary>
        [RegisterProperty]
        public HeaderFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Header fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class HeaderFields : AbstractHierarchicalObject<HeaderFields>
        {
            /// <summary>
            /// The content item of type Header that is a target of the extended API.
            /// </summary>
            private readonly Header mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="HeaderFields" /> class with the specified content item of type Header.
            /// </summary>
            /// <param name="instance">The content item of type Header that is a target of the extended API.</param>
            public HeaderFields(Header instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// HeaderID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.HeaderID;
                }
                set
                {
                    mInstance.HeaderID = value;
                }
            }


            /// <summary>
            /// Node Name.
            /// </summary>
            public string Name
            {
                get
                {
                    return mInstance.HeaderName;
                }
                set
                {
                    mInstance.HeaderName = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Header" /> class.
        /// </summary>
        public Header() : base(CLASS_NAME)
        {
            mFields = new HeaderFields(this);
        }

        #endregion
    }
}