//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.PartialWidgetPage;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TestChild.CLASS_NAME, typeof(TestChild))]

namespace CMS.DocumentEngine.Types.PartialWidgetPage
{
	/// <summary>
	/// Represents a content item of type TestChild.
	/// </summary>
	public partial class TestChild : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "PartialWidgetPage.TestChild";


		/// <summary>
		/// The instance of the class that provides extended API for working with TestChild fields.
		/// </summary>
		private readonly TestChildFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// TestChildID.
		/// </summary>
		[DatabaseIDField]
		public int TestChildID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("TestChildID"), 0);
			}
			set
			{
				SetValue("TestChildID", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TestChild fields.
		/// </summary>
		[RegisterProperty]
		public TestChildFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with TestChild fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TestChildFields : AbstractHierarchicalObject<TestChildFields>
		{
			/// <summary>
			/// The content item of type TestChild that is a target of the extended API.
			/// </summary>
			private readonly TestChild mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TestChildFields" /> class with the specified content item of type TestChild.
			/// </summary>
			/// <param name="instance">The content item of type TestChild that is a target of the extended API.</param>
			public TestChildFields(TestChild instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// TestChildID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.TestChildID;
				}
				set
				{
					mInstance.TestChildID = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TestChild" /> class.
		/// </summary>
		public TestChild() : base(CLASS_NAME)
		{
			mFields = new TestChildFields(this);
		}

		#endregion
	}
}